### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by ghost** [ldelgadoIII/prj-rev-bwfs-dasmoto#4]
Satisfactory 👍 

You didn't follow the design specification, but it looks like you've got a good handle on some fundamental CSS properties. Good job! 

Try to refactor your code a bit so it's more organized. Use container divs in your HTML to group related sections of code and fix the indentation, and always strive to eliminate repetition from your CSS. Keeping your code clean and DRY is just as important as getting the page working.

In the future, try to keep to the design specification as close as possible. I know as a developer you want to exercise your own creative license, but the point of these projects is to emulate the very common real life scenario of working with a designer and having to produce a website exactly according to the design specification. It's not enough to just know HTML and CSS, you need to satisfy your client's requirements and work as part of a team.

**Comment by ldelgadoIII** [comment]
Thank you so much for your all your advice! This has been really helpful and will definitely keep it all in mind for the future.
